version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env  # Points to your .env file to load environment variables
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 80
